name: agro_app
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^6.1.1
  get: ^3.13.2
  http: ^0.12.2
  intl: ^0.16.1
  fluttericon: ^1.0.7
  shared_preferences: ^0.5.12+2
  provider: ^4.3.2+2
  flutter_spinkit: ^4.1.2+1
  uuid: ^2.2.2
  upgrader: ^2.5.0
  modal_progress_hud: ^0.1.3
  syncfusion_flutter_gauges: ^18.2.57

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.jpg
    - assets/images/bad-weather.png
    - assets/images/pest-observation.png
    - assets/images/trowel.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Spartan MB
      fonts:
        - asset: assets/fonts/SpartanMB-Black.otf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Italic-VariableFont_wght.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
